### ISSUE TITLE
Increase MTU for voice

### ISSUE THREAD

**Issue by hibatos** [Yanndroid/SiriRemote-Linux#2]
Hi @Yanndroid,
I just found your project and I am so happy I did.
I tried to implement this for over two years now, but I could not get it to work (I could not implement the exchange gatttool made with the remote because of some reason still unknown to me),

Reading in your README about the problems with audio decoding caused by dropped bits,
after a bit of research it seems to not actually be that difficult to overcome, if - and only if - the problem is caused by the BLE default MTU of 27 bytes.

have you tried that yet or is that possibly a fix that I should try to implement?

Best regards and thanks from Germany

**Comment by Yanndroid** [comment]
Hi there,
I actually already fixed the bluez limitation by directly using HCI and rebuilding the ACL Packets myself, but I'm still having a couple of other problems and it's been quite while since I've worked on this.
One of the problems was that some other program was force disconnecting my remote (I believe bluez) and the other is that after a couple of second only every third audio frame is received and for this I have absolutely no idea why it's happening.

As I said in the other issue, I want to work more on this again, but I'll need some time understand my own code again :sweat_smile: . If I get it cleaned up, I can push it to a dev branch so you can have a look too.

**Comment by hibatos** [comment]
Hi,
that would be super cool, thank you!

**Comment by Yanndroid** [comment]
Hey there,
I'm currently working on a Kernel Module for the remotes and came across the audio issue again. And you were right, the MTU is actually one of the issues, but not in the way one might think 😅 ... The remote does not accept any other MTU than 23, so there's nothing I can do about that. Even on MacOS it sticks to 23, but the difference there is that MacOS (and Windows too, I think) don't care, it's a Linux (bluez) issue:

On Linux, when the device reports it's MTU, bluez will truncate every packet to that size, no matter how many bytes are received, whereas MacOS, just takes everything it gets. [Here](https://github.com/bluez/bluez/blob/6b0a08776ae44a9102d7c6875a77e83dc6a11a37/src/shared/att.c#L1047)'s the code line where it happens. Unfortunately, this is intended behaviour according to the official Bluetooth specs and thus won't be changed (there's actually already an [issue](https://github.com/bluez/bluez/issues/576) for this exact thing), but we can patch it locally and I think the newer remotes report their MTU correctly.

But... even with this fixed, I still have the issue that, after a few seconds, entire frames are dropped. And this is not a hardware issue, as it works in a MacOS VM. Probably a bluez problem again :(
